name: Continuous Integration
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-port: 6379
          redis-version: "6.x"
          auto-start: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Set up dependencies
        run: uv sync -p ${{ matrix.python-version }}

      - name: Run tests
        run: |
          uv run tests/fixtures/setup_fixtures.py
          uv run pytest -W error

      - name: Report coverage with Codecov
        if: github.event_name == 'push' && matrix.python-version == 3.13 && matrix.os == 'ubuntu-24.04'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }} && matrix.python-version == 3.13 && matrix.os == 'ubuntu-24.04'
        uses: codecov/test-results-action@v1

      - name: SonarQube Scan
        if: matrix.python-version == 3.13 && matrix.os == 'ubuntu-24.04'
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
