name: Continuous Integration
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('**/pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ matrix.python-version }}-

      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1.31.1
        with:
          redis-port: 6379
          redis-version: "6.x"
          auto-start: true

      - name: Setup server
        run: |
          pdm sync -G dev

      - name: Run tests
        run: |
          pdm run fixtures
          pdm run test

      - name: Report coverage with Codecov
        if: github.event_name == 'push' && matrix.python-version == 3.11 && matrix.os == 'ubuntu-22.04'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests

      - name: Override Coverage Source Path for Sonar
        if: matrix.python-version == 3.11 && matrix.os == 'ubuntu-22.04'
        run: sed -i "s/<source>\/home\/runner\/work\/Vremenar-API\/Vremenar-API<\/source>/<source>\/github\/workspace<\/source>/g" coverage.xml

      - name: SonarCloud Scan
        if: matrix.python-version == 3.11 && matrix.os == 'ubuntu-22.04'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-staging:
    runs-on: ubuntu-22.04
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: Staging

    steps:
      - name: Deploy
        run: |
          echo "Deploying to staging..."
